export const blogPosts = [
	{
		id: 1,
		title: 'Getting Started with Node.js in 2026',
		slug: 'getting-started-with-nodejs-2026',
		excerpt:
			'A beginner-friendly guide to setting up your first Node.js project and understanding the basics.',
		content:
			'Node.js is a JavaScript runtime that lets you run JavaScript on the server. Start by installing Node, initializing your project with npm, and creating a simple HTTP server. As you grow, explore frameworks like Express and tools like nodemon for faster development.',
		author: 'Asif Nawaz',
		category: 'Backend',
		tags: ['nodejs', 'javascript', 'backend'],
		coverImage: 'https://picsum.photos/seed/nodejs/800/400',
		publishedAt: '2026-01-10T09:30:00.000Z',
		readTime: 6,
		likes: 124,
		commentsCount: 18,
		featured: true,
		status: 'published',
	},
	{
		id: 2,
		title: 'Understanding REST API Design',
		slug: 'understanding-rest-api-design',
		excerpt:
			'Learn the practical principles behind designing clean and maintainable REST APIs.',
		content:
			'Good REST API design starts with resource naming, consistent HTTP methods, and proper status codes. Keep endpoints predictable, use validation, and return helpful error messages. Version your APIs when introducing breaking changes.',
		author: 'Sara Khan',
		category: 'API',
		tags: ['rest', 'api', 'design'],
		coverImage: 'https://picsum.photos/seed/restapi/800/400',
		publishedAt: '2026-01-14T11:00:00.000Z',
		readTime: 8,
		likes: 96,
		commentsCount: 10,
		featured: false,
		status: 'published',
	},
	{
		id: 3,
		title: 'JavaScript Array Methods You Should Know',
		slug: 'javascript-array-methods-you-should-know',
		excerpt:
			'A quick tour of map, filter, reduce, and other powerful array helpers in JavaScript.',
		content:
			'Array methods can make your code cleaner and more expressive. Use map for transformations, filter for selecting values, and reduce for combining results. Practice with real examples to build strong intuition.',
		author: 'Hamza Ali',
		category: 'JavaScript',
		tags: ['javascript', 'arrays', 'tips'],
		coverImage: 'https://picsum.photos/seed/jsarray/800/400',
		publishedAt: '2026-01-20T08:20:00.000Z',
		readTime: 5,
		likes: 143,
		commentsCount: 22,
		featured: true,
		status: 'published',
	},
	{
		id: 4,
		title: 'How to Structure an Express Project',
		slug: 'how-to-structure-an-express-project',
		excerpt:
			'A practical folder structure for scalable Express applications.',
		content:
			'As your app grows, organize code into routes, controllers, services, models, and middlewares. Keep business logic out of routes. Add environment-based config and central error handling to make maintenance easier.',
		author: 'Maham Fatima',
		category: 'Backend',
		tags: ['express', 'architecture', 'nodejs'],
		coverImage: 'https://picsum.photos/seed/express/800/400',
		publishedAt: '2026-01-24T14:45:00.000Z',
		readTime: 7,
		likes: 88,
		commentsCount: 9,
		featured: false,
		status: 'published',
	},
	{
		id: 5,
		title: 'Intro to MongoDB for Beginners',
		slug: 'intro-to-mongodb-for-beginners',
		excerpt:
			'Understand collections, documents, and basic CRUD in MongoDB.',
		content:
			'MongoDB is a NoSQL database that stores data as JSON-like documents. Start with creating collections and inserting records, then move to queries, updates, and indexes. Mongoose can help you model data in Node.js apps.',
		author: 'Zainab Iqbal',
		category: 'Database',
		tags: ['mongodb', 'nosql', 'database'],
		coverImage: 'https://picsum.photos/seed/mongodb/800/400',
		publishedAt: '2026-02-01T10:10:00.000Z',
		readTime: 9,
		likes: 112,
		commentsCount: 14,
		featured: false,
		status: 'published',
	},
	{
		id: 6,
		title: 'Authentication with JWT in Express',
		slug: 'authentication-with-jwt-in-express',
		excerpt:
			'Secure your APIs using JSON Web Tokens and middleware-based authorization.',
		content:
			'JWT authentication usually includes login, token generation, and protected routes. Store secrets securely, use short-lived tokens, and validate tokens in middleware. Consider refresh tokens for better user experience.',
		author: 'Bilal Ahmed',
		category: 'Security',
		tags: ['jwt', 'auth', 'express'],
		coverImage: 'https://picsum.photos/seed/jwt/800/400',
		publishedAt: '2026-02-05T16:30:00.000Z',
		readTime: 10,
		likes: 175,
		commentsCount: 31,
		featured: true,
		status: 'published',
	},
	{
		id: 7,
		title: 'Error Handling Best Practices in APIs',
		slug: 'error-handling-best-practices-in-apis',
		excerpt:
			'Make your API errors consistent, debuggable, and developer-friendly.',
		content:
			'Use a centralized error handler and return consistent error shapes. Avoid leaking sensitive details in production. Include useful metadata like error codes and request IDs for easier debugging.',
		author: 'Usman Tariq',
		category: 'API',
		tags: ['errors', 'api', 'best-practices'],
		coverImage: 'https://picsum.photos/seed/errors/800/400',
		publishedAt: '2026-02-09T07:50:00.000Z',
		readTime: 6,
		likes: 67,
		commentsCount: 6,
		featured: false,
		status: 'published',
	},
	{
		id: 8,
		title: 'Deploying a Node.js App to a VPS',
		slug: 'deploying-a-nodejs-app-to-a-vps',
		excerpt:
			'Step-by-step guide to deploy your Node.js backend on a Linux VPS.',
		content:
			'Prepare your server, install Node.js, clone your code, and manage your app with PM2. Set up Nginx as a reverse proxy and enable HTTPS. Monitor logs and resource usage to keep your app healthy.',
		author: 'Areeba Noor',
		category: 'DevOps',
		tags: ['deployment', 'nodejs', 'linux'],
		coverImage: 'https://picsum.photos/seed/deploy/800/400',
		publishedAt: '2026-02-12T13:15:00.000Z',
		readTime: 11,
		likes: 153,
		commentsCount: 19,
		featured: true,
		status: 'published',
	},
	{
		id: 9,
		title: 'Mastering Async/Await in JavaScript',
		slug: 'mastering-async-await-in-javascript',
		excerpt:
			'Write cleaner asynchronous code using async/await with proper error handling.',
		content:
			'Async/await makes promise-based code easier to read. Always wrap awaited operations in try/catch where failures are expected, and avoid blocking loops by using Promise.all when tasks can run in parallel.',
		author: 'Nimra Saleem',
		category: 'JavaScript',
		tags: ['javascript', 'async', 'promises'],
		coverImage: 'https://picsum.photos/seed/asyncawait/800/400',
		publishedAt: '2026-02-14T09:00:00.000Z',
		readTime: 7,
		likes: 119,
		commentsCount: 13,
		featured: false,
		status: 'published',
	},
	{
		id: 10,
		title: 'Pagination Strategies for REST APIs',
		slug: 'pagination-strategies-for-rest-apis',
		excerpt:
			'Compare offset and cursor pagination approaches for scalable API responses.',
		content:
			'Offset pagination is simple but can become slow on large datasets. Cursor pagination performs better for big tables and real-time data updates. Choose based on your data size, query patterns, and consistency needs.',
		author: 'Saad Irfan',
		category: 'API',
		tags: ['api', 'pagination', 'backend'],
		coverImage: 'https://picsum.photos/seed/pagination/800/400',
		publishedAt: '2026-02-16T12:40:00.000Z',
		readTime: 8,
		likes: 85,
		commentsCount: 7,
		featured: false,
		status: 'published',
	},
	{
		id: 11,
		title: 'Mongoose Schema Design Tips',
		slug: 'mongoose-schema-design-tips',
		excerpt:
			'Learn practical schema design patterns for maintainable MongoDB models.',
		content:
			'Design schemas around your query needs. Use indexes on frequently searched fields, validate inputs at schema level, and keep document size reasonable by embedding only when data is tightly related.',
		author: 'Hira Javed',
		category: 'Database',
		tags: ['mongoose', 'mongodb', 'schema'],
		coverImage: 'https://picsum.photos/seed/mongoose/800/400',
		publishedAt: '2026-02-18T15:20:00.000Z',
		readTime: 9,
		likes: 101,
		commentsCount: 11,
		featured: true,
		status: 'published',
	},
	{
		id: 12,
		title: 'Environment Variables in Node.js',
		slug: 'environment-variables-in-nodejs',
		excerpt:
			'Manage configuration safely using environment variables across environments.',
		content:
			'Environment variables keep secrets and config out of source code. Use a package like dotenv during development, and ensure production values are managed by your hosting platform. Validate required env vars on app startup.',
		author: 'Ali Raza',
		category: 'Backend',
		tags: ['nodejs', 'env', 'configuration'],
		coverImage: 'https://picsum.photos/seed/envvars/800/400',
		publishedAt: '2026-02-19T10:35:00.000Z',
		readTime: 5,
		likes: 92,
		commentsCount: 8,
		featured: false,
		status: 'published',
	},
	{
		id: 13,
		title: 'Rate Limiting Express APIs',
		slug: 'rate-limiting-express-apis',
		excerpt:
			'Protect your endpoints from abuse with simple and effective rate limiting.',
		content:
			'Rate limiting helps defend your API against brute-force and spam traffic. Apply sensible per-minute limits, customize messages for clients, and combine with logging and monitoring to detect unusual request patterns early.',
		author: 'Farhan Yousaf',
		category: 'Security',
		tags: ['security', 'express', 'rate-limit'],
		coverImage: 'https://picsum.photos/seed/ratelimit/800/400',
		publishedAt: '2026-02-20T08:15:00.000Z',
		readTime: 6,
		likes: 130,
		commentsCount: 16,
		featured: true,
		status: 'published',
	},
	{
		id: 14,
		title: 'Building Reusable Middleware in Express',
		slug: 'building-reusable-middleware-in-express',
		excerpt:
			'Create reusable middleware patterns for validation, auth, and logging.',
		content:
			'Middleware keeps request handling modular. Build small focused middleware functions for authentication, schema validation, and request logging. Compose them by route to keep controllers clean and testable.',
		author: 'Iqra Mahmood',
		category: 'Backend',
		tags: ['express', 'middleware', 'architecture'],
		coverImage: 'https://picsum.photos/seed/middleware/800/400',
		publishedAt: '2026-02-22T14:05:00.000Z',
		readTime: 7,
		likes: 109,
		commentsCount: 12,
		featured: false,
		status: 'published',
	},
	{
		id: 15,
		title: 'Logging and Monitoring for Node.js Apps',
		slug: 'logging-and-monitoring-for-nodejs-apps',
		excerpt:
			'Track errors and performance with practical logging and monitoring basics.',
		content:
			'Use structured logs to make searching easier and include useful context like request ID and route. Add monitoring for uptime, response times, and error rates. Alerts help you react quickly before users are affected.',
		author: 'Tayyab Malik',
		category: 'DevOps',
		tags: ['logging', 'monitoring', 'nodejs'],
		coverImage: 'https://picsum.photos/seed/monitoring/800/400',
		publishedAt: '2026-02-24T17:25:00.000Z',
		readTime: 8,
		likes: 141,
		commentsCount: 20,
		featured: true,
		status: 'published',
	},
];

export const users = [
	{
		id: 1,
		name: 'Asif Nawaz',
		email: 'asif.nawaz@example.com',
		username: 'asifnawaz',
		role: 'admin',
		bio: 'Backend developer and technical writer.',
		avatar: 'https://picsum.photos/seed/user1/200/200',
		isActive: true,
		joinedAt: '2025-11-10T09:30:00.000Z',
	},
	{
		id: 2,
		name: 'Sara Khan',
		email: 'sara.khan@example.com',
		username: 'sarakhan',
		role: 'author',
		bio: 'API design enthusiast and mentor.',
		avatar: 'https://picsum.photos/seed/user2/200/200',
		isActive: true,
		joinedAt: '2025-12-02T12:00:00.000Z',
	},
	{
		id: 3,
		name: 'Hamza Ali',
		email: 'hamza.ali@example.com',
		username: 'hamzaali',
		role: 'author',
		bio: 'JavaScript tips and tutorials creator.',
		avatar: 'https://picsum.photos/seed/user3/200/200',
		isActive: true,
		joinedAt: '2025-12-15T08:15:00.000Z',
	},
	{
		id: 4,
		name: 'Maham Fatima',
		email: 'maham.fatima@example.com',
		username: 'mahamfatima',
		role: 'author',
		bio: 'Clean architecture advocate for Node.js apps.',
		avatar: 'https://picsum.photos/seed/user4/200/200',
		isActive: true,
		joinedAt: '2026-01-04T10:45:00.000Z',
	},
	{
		id: 5,
		name: 'Zainab Iqbal',
		email: 'zainab.iqbal@example.com',
		username: 'zainabiqbal',
		role: 'author',
		bio: 'Database-focused engineer and educator.',
		avatar: 'https://picsum.photos/seed/user5/200/200',
		isActive: true,
		joinedAt: '2026-01-10T14:20:00.000Z',
	},
	{
		id: 6,
		name: 'Bilal Ahmed',
		email: 'bilal.ahmed@example.com',
		username: 'bilalahmed',
		role: 'author',
		bio: 'Security-focused backend developer.',
		avatar: 'https://picsum.photos/seed/user6/200/200',
		isActive: true,
		joinedAt: '2026-01-17T07:50:00.000Z',
	},
	{
		id: 7,
		name: 'Usman Tariq',
		email: 'usman.tariq@example.com',
		username: 'usmantariq',
		role: 'author',
		bio: 'Builds reliable APIs and error handling systems.',
		avatar: 'https://picsum.photos/seed/user7/200/200',
		isActive: false,
		joinedAt: '2026-01-22T16:10:00.000Z',
	},
	{
		id: 8,
		name: 'Areeba Noor',
		email: 'areeba.noor@example.com',
		username: 'areebanoor',
		role: 'author',
		bio: 'DevOps learner sharing deployment guides.',
		avatar: 'https://picsum.photos/seed/user8/200/200',
		isActive: true,
		joinedAt: '2026-01-29T11:35:00.000Z',
	},
	{
		id: 9,
		name: 'Nimra Saleem',
		email: 'nimra.saleem@example.com',
		username: 'nimrasaleem',
		role: 'author',
		bio: 'Writes about async JavaScript and performance.',
		avatar: 'https://picsum.photos/seed/user9/200/200',
		isActive: true,
		joinedAt: '2026-02-02T09:25:00.000Z',
	},
	{
		id: 10,
		name: 'Saad Irfan',
		email: 'saad.irfan@example.com',
		username: 'saadirfan',
		role: 'reader',
		bio: 'Backend engineer interested in scalable APIs.',
		avatar: 'https://picsum.photos/seed/user10/200/200',
		isActive: true,
		joinedAt: '2026-02-10T13:40:00.000Z',
	},
];
